# 登录用
User:
  mobile :  '139**21'
  password: '123123'
  # 登录后再请求报文可以看到
  authentication :  '123123123'
  # 指定乘客信息[不填默认所有联系人]
  passengers:
     - 张三

# 出发点
From: nanpu
# 到达点
To: gouqi
# 购买日期
Date: '2024-01-01'

# 定制化
Customization:
  # 汽车最晚的开车时间
  LatestBusTime: '23:59'
  # 船最晚的开车时间
  LatestShipTime: '23:59'
  # 最早上船时间
  MinShipTime: '06:00'
  # 指定航班
  LineNum: ''
  # 指定舱位
  Class: ''

# 目的地字典
PortNo:
  nanpu: 1046
  shengshan: 1016
  shengsi: 1010
  huaniao: 1014
  gouqi: 1017

Notice:
  flag: false
  companyWx: ""


