# 登录用
User:
  mobile :  '139**21'
  password: '123123'
  # 登录后再请求报文可以看到
  authentication :  '123123123'
  # 指定乘客信息[不填默认所有联系人]
  passengers:
     - 张三
# 目的地字典
PortNo:
  nanpu: 1046
  gouqi: 1017
dingtalk_url: 'https://oapi.dingtalk.com/robot/send?access_token=xxxxxx"'
dingtalk_keyword: "xxxx"
